import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar order of the top-level sections (spec-core, spec-general,
// spec-rail, spec-security, glossary) is controlled by the `position` field
// in each section's `_category_.json`, generated by
// scripts/sync-specification.mjs from the `specification` submodule.
const sidebars: SidebarsConfig = {
  specSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
